# Generated by Django 5.0.2 on 2024-02-14 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('cod_fiscal', models.CharField(max_length=10)),
                ('cod_onrc', models.CharField(max_length=255)),
                ('adresa', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'partner',
            },
        ),
        migrations.CreateModel(
            name='PartnerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.partners')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='partners',
            name='user',
            field=models.ManyToManyField(related_name='PartnersUsers', through='billing_app.PartnerUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='YourCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255, unique=True)),
                ('cod_fiscal', models.CharField(max_length=10, unique=True)),
                ('cod_onrc', models.CharField(max_length=255, unique=True)),
                ('judet', models.CharField(max_length=255)),
                ('localitate', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255, null=True)),
                ('street_no', models.CharField(max_length=20, null=True)),
                ('tva', models.CharField(choices=[('Platitor', 'Platitor'), ('Neplatitor', 'Neplatitor')], max_length=10)),
                ('address_other_info', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'your_company',
            },
        ),
        migrations.CreateModel(
            name='ExitInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=5)),
                ('number', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('product_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vat_rate', models.CharField(choices=[('19%', '19%'), ('9%', '9%'), ('5%', '5%'), ('0%', '0%')], max_length=3)),
                ('vat_ammount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.partners')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.yourcompany')),
            ],
            options={
                'db_table': 'exit_invoice',
            },
        ),
        migrations.CreateModel(
            name='EntryInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=5)),
                ('number', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('product_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vat_rate', models.CharField(choices=[('19%', '19%'), ('9%', '9%'), ('5%', '5%'), ('0%', '0%')], max_length=3)),
                ('vat_ammount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.partners')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.yourcompany')),
            ],
            options={
                'db_table': 'entry_invoice',
            },
        ),
    ]
