# Generated by Django 5.0.2 on 2024-02-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryinvoice',
            name='vat_rate',
            field=models.FloatField(choices=[(0.19, 19), (0.09, 9), (0.05, 5), (0, 0)]),
        ),
        migrations.AlterField(
            model_name='exitinvoice',
            name='vat_rate',
            field=models.FloatField(choices=[(0.19, 19), (0.09, 9), (0.05, 5), (0, 0)]),
        ),
    ]
